// <auto-generated />
using System;
using HMIS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HMIS.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HMIS.Models.PersonAdderess", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Address1")
                        .HasColumnType("text")
                        .HasColumnName("Address1");

                    b.Property<string>("Address2")
                        .HasColumnType("text")
                        .HasColumnName("Address2");

                    b.Property<int?>("PersonMasterid")
                        .HasColumnType("integer");

                    b.Property<string>("city")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("created_location_id")
                        .HasColumnType("integer")
                        .HasColumnName("created_location_id");

                    b.Property<int>("created_user_id")
                        .HasColumnType("integer")
                        .HasColumnName("created_user_id");

                    b.Property<string>("distict")
                        .HasColumnType("text")
                        .HasColumnName("distict");

                    b.Property<int>("is_active")
                        .HasColumnType("integer")
                        .HasColumnName("is_active");

                    b.Property<int>("is_deleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int>("modified_location_id")
                        .HasColumnType("integer")
                        .HasColumnName("modified_location_id");

                    b.Property<int>("modified_user_id")
                        .HasColumnType("integer")
                        .HasColumnName("modified_user_id");

                    b.Property<int>("person_id")
                        .HasColumnType("integer")
                        .HasColumnName("PersonMasterId");

                    b.Property<string>("postal_code")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("postal_code");

                    b.Property<string>("state")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("id");

                    b.HasIndex("PersonMasterid");

                    b.ToTable("person_address_m");
                });

            modelBuilder.Entity("HMIS.Models.PersonMaster", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("BirthSex")
                        .HasColumnType("text")
                        .HasColumnName("BirthSex");

                    b.Property<int?>("DLNumber")
                        .HasColumnType("integer")
                        .HasColumnName("DLNumber");

                    b.Property<int>("Ethnicity")
                        .HasColumnType("integer")
                        .HasColumnName("Ethnicity");

                    b.Property<bool>("IsMarried")
                        .HasColumnType("boolean")
                        .HasColumnName("IsMarried");

                    b.Property<string>("L_name")
                        .HasColumnType("text")
                        .HasColumnName("L_name");

                    b.Property<int?>("Mobile")
                        .HasColumnType("integer")
                        .HasColumnName("Mobile");

                    b.Property<string>("Name_Nickname")
                        .HasColumnType("text")
                        .HasColumnName("Name_Nickname");

                    b.Property<string>("Name_prefix")
                        .HasColumnType("text")
                        .HasColumnName("Name_prefix");

                    b.Property<string>("Name_suffix")
                        .HasColumnType("text")
                        .HasColumnName("Name_suffix");

                    b.Property<string>("Name_text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name_text");

                    b.Property<int>("NationalIDNumber")
                        .HasColumnType("integer")
                        .HasColumnName("NationalIDNumber");

                    b.Property<int?>("PassortNumber")
                        .HasColumnType("integer")
                        .HasColumnName("PassortNumber");

                    b.Property<int?>("Phone_Home")
                        .HasColumnType("integer")
                        .HasColumnName("Phone_Home");

                    b.Property<int?>("Phone_Work")
                        .HasColumnType("integer")
                        .HasColumnName("Phone_Work");

                    b.Property<string>("Photo")
                        .HasColumnType("text")
                        .HasColumnName("Photo");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Race");

                    b.Property<string>("S_name")
                        .HasColumnType("text")
                        .HasColumnName("S_name");

                    b.Property<DateTime>("birthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthDate");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int?>("created_location_id")
                        .HasColumnType("integer")
                        .HasColumnName("created_location_id");

                    b.Property<int?>("created_user_id")
                        .HasColumnType("integer")
                        .HasColumnName("created_user_id");

                    b.Property<DateTime>("deceasedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deceasedDateTime");

                    b.Property<bool>("deceased_YN")
                        .HasColumnType("boolean")
                        .HasColumnName("deceased_YN");

                    b.Property<string>("email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("email_work")
                        .HasColumnType("text")
                        .HasColumnName("email_work");

                    b.Property<string>("gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<int?>("id_number")
                        .HasColumnType("integer")
                        .HasColumnName("id_number");

                    b.Property<int?>("id_type")
                        .HasColumnType("integer")
                        .HasColumnName("id_type");

                    b.Property<int?>("is_active")
                        .HasColumnType("integer")
                        .HasColumnName("is_active");

                    b.Property<int?>("is_deleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<int>("language_1")
                        .HasColumnType("integer")
                        .HasColumnName("language_1");

                    b.Property<int>("language_2")
                        .HasColumnType("integer")
                        .HasColumnName("language_2");

                    b.Property<DateTime?>("modified_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int?>("modified_location_id")
                        .HasColumnType("integer")
                        .HasColumnName("modified_location_id");

                    b.Property<int?>("modified_user_id")
                        .HasColumnType("integer")
                        .HasColumnName("modified_user_id");

                    b.Property<string>("natioanlity")
                        .HasColumnType("text")
                        .HasColumnName("natioanlity");

                    b.HasKey("id");

                    b.ToTable("person_m");
                });

            modelBuilder.Entity("HMIS.Models.SecurityUserMaster", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("can_change_pwd")
                        .HasColumnType("boolean")
                        .HasColumnName("can_change_pwd");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("created_location_id")
                        .HasColumnType("integer")
                        .HasColumnName("created_location_id");

                    b.Property<int>("created_user_id")
                        .HasColumnType("integer")
                        .HasColumnName("created_user_id");

                    b.Property<int>("is_active")
                        .HasColumnType("integer")
                        .HasColumnName("is_active");

                    b.Property<int>("is_deleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int>("modified_location_id")
                        .HasColumnType("integer")
                        .HasColumnName("modified_location_id");

                    b.Property<int>("modified_user_id")
                        .HasColumnType("integer")
                        .HasColumnName("modified_user_id");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("staff_id")
                        .HasColumnType("integer")
                        .HasColumnName("staff_id");

                    b.Property<int>("tenent_id")
                        .HasColumnType("integer")
                        .HasColumnName("tenent_id");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<DateTime>("valid_from")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime>("valid_to")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("id");

                    b.ToTable("sec_user_m");
                });

            modelBuilder.Entity("HMIS.Models.ServiceCenter", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("created_location_id")
                        .HasColumnType("integer")
                        .HasColumnName("created_location_id");

                    b.Property<int>("created_user_id")
                        .HasColumnType("integer")
                        .HasColumnName("created_user_id");

                    b.Property<int>("department_id")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("desc");

                    b.Property<int>("is_active")
                        .HasColumnType("integer")
                        .HasColumnName("is_active");

                    b.Property<int>("is_deleted")
                        .HasColumnType("integer")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int>("modified_location_id")
                        .HasColumnType("integer")
                        .HasColumnName("modified_location_id");

                    b.Property<int>("modified_user_id")
                        .HasColumnType("integer")
                        .HasColumnName("modified_user_id");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int>("type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("id");

                    b.ToTable("Service_Center_m");
                });

            modelBuilder.Entity("HMIS.Models.PersonAdderess", b =>
                {
                    b.HasOne("HMIS.Models.PersonMaster", null)
                        .WithMany("PersonAdderess")
                        .HasForeignKey("PersonMasterid");
                });

            modelBuilder.Entity("HMIS.Models.PersonMaster", b =>
                {
                    b.Navigation("PersonAdderess");
                });
#pragma warning restore 612, 618
        }
    }
}
